name: admin_panel
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  get: ^4.6.6
  gap: ^3.0.1
  dio: ^5.8.0+1
  logger: ^2.5.0
  flutter_secure_storage: ^9.2.4
  http: ^1.3.0
  flutter_animate: ^4.5.2
  url_strategy: ^0.3.0
  cached_network_image: ^3.4.1
  data_table_2: ^2.5.18


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/logos/